# Generated by Django 5.0 on 2024-02-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_tvset'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collections',
        ),
        migrations.DeleteModel(
            name='Tvset',
        ),
    ]
